name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: ZIP dosyasını aç
        run: unzip ZombieRush3D_Android_Project_v3_5_REAL_9MM_PISTOL_COMBAT_UPGRADE.zip

      - name: Java kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4

      - name: APK oluştur
        run: |
          cd ZombieRush3D_Android_Project_v3_5_REAL_9MM_PISTOL_COMBAT_UPGRADE
          gradle assembleDebug

      - name: APK dosyasını yükle
        uses: actions/upload-artifact@v4
        with:
          name: ZombieRush3D-v3-5-REAL-9MM-PISTOL-COMBAT-UPGRADE-debug-apk
          path: ZombieRush3D_Android_Project_v3_5_REAL_9MM_PISTOL_COMBAT_UPGRADE/app/build/outputs/apk/debug/*.apk
