name: Build APK
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ZIP ac
        run: unzip -o -q ZombieRush3D_v2*.zip
      - name: Gereksiz kutuphaneyi kaldir
        run: |
          sed -i '/appcompat/d' ZombieRush3D_v2/app/build.gradle
          cat ZombieRush3D_v2/app/build.gradle
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle indir
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip -q gradle-8.5-bin.zip
      - name: APK Build
        run: |
          cd ZombieRush3D_v2
          ../gradle-8.5/bin/gradle assembleDebug --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: ZombieRush3D-APK
          path: ZombieRush3D_v2/app/build/outputs/apk/debug/app-debug.apk
